   - name: Run Security Scan
        run: |
          curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.3/dependency-check-6.5.3-release.zip
          unzip dependency-check-6.5.3-release.zip
          ./dependency-check/bin/dependency-check.sh --project JavaSecurityCheck --scan ./ --format HTML --out report/dependency-check-report.html

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: report/dependency-check-report.html
